services:
  cockroachdb:
    image: cockroachdb/cockroach:latest
    ports:
      - "26257:26257"
    environment:
      - COCKROACH_USER=cockroach
      - COCKROACH_PASSWORD=arthropod
      - COCKROACH_DATABASE=roach
    command: ["start-single-node"]